version: '3.8'

services:
    php:
        restart: unless-stopped
        container_name: ${CONTAINER_PREFIX}_php
        build:
            context: ./services/php/fpm
            args:
                PROJECT_NAME: ${PROJECT_NAME}
                GITHUB_USER: ${GITHUB_USER}
                GITHUB_TOKEN: ${GITHUB_TOKEN}
                GITHUB_EMAIL: ${GITHUB_EMAIL}
                GITHUB_NAME: ${GITHUB_NAME}
                NPM_TOKEN: ${NPM_TOKEN}
        expose:
            - '9000'
        volumes:
            - ./services/php/fpm/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./services/php/fpm/bashrc_config.txt:/usr/local/share/bashrc_config.txt
            - ./app:/var/www/${PROJECT_NAME}
            - ./services/composer/cache:/root/.composer/cache
        environment:
            - PHP_IDE_CONFIG=serverName=${PROJECT_NAME}
            - TIMEZONE=${TIMEZONE}
            - XDEBUG_CLIENT_HOST=${XDEBUG_CLIENT_HOST}
            - COMPOSER_AUTH={"github-oauth":{"github.com":"${GITHUB_TOKEN}"}}
        networks:
            - default

    nginx:
        restart: unless-stopped
        container_name: ${CONTAINER_PREFIX}_nginx
        image: nginx:1.21.6-alpine
        ports:
            - '${NGINX_PORT}:80'
            - '${NGINX_SSL_PORT}:443'
        env_file:
            - .env
        volumes:
            - ./services/nginx:/etc/nginx/templates
            - ./services/ssl:/etc/ssl
            - ./app:/var/www/${PROJECT_NAME}
        environment:
            - PROJECT_NAME=${PROJECT_NAME}
            - PATH_TO_ROOT=${PATH_TO_ROOT}
        networks:
            - default

    mysql:
        restart: unless-stopped
        container_name: ${CONTAINER_PREFIX}_mysql
        image: mysql:8.0.28
        ports:
            - '${MYSQL_PORT}:3306'
        env_file:
            - .env
        volumes:
            - ./services/mysql/config/my.cnf:/etc/mysql/conf.d/my.cnf
            - ./services/mysql/data:/var/lib/mysql
        networks:
            - default

    pgsql:
        restart: unless-stopped
        container_name: ${CONTAINER_PREFIX}_pgsql
        image: postgres:14.2-alpine
        ports:
            - '${POSTGRES_PORT}:5432'
        env_file:
            - .env
        environment:
            - PGDATA=/var/lib/postgresql/db/pgdata
        volumes:
            - ./services/pgsql/data:/var/lib/postgresql/db/data
        networks:
            - default

    redis:
        restart: unless-stopped
        container_name: ${CONTAINER_PREFIX}_redis
        image: redis:6.2.6-alpine
        expose:
            - '6379'
        volumes:
            - ./app:/var/www/${PROJECT_NAME}
            - ./services/redis/data:/data
            - ./services/redis/config/redis.conf:/usr/local/etc/redis/redis.conf
        command: redis-server /usr/local/etc/redis/redis.conf
        networks:
            - default

#    elasticsearch:
#        container_name: ${CONTAINER_PREFIX}_elasticsearch
#        image: elasticsearch:7.10.1
#        expose:
#            - '9200'
#        environment:
#            - ES_JAVA_OPTS=-Xms512m -Xmx512m
#        volumes:
#            - ./app:/var/www/${PROJECT_NAME}
#            - ./services/elasticsearch/data:/usr/share/elasticsearch/data
#            - ./services/elasticsearch/config/elastic.yml:/usr/share/elasticsearch/config/elasticsearch.yml
#        networks:
#            - default

    opensearch:
        container_name: ${CONTAINER_PREFIX}_opensearch
        image: opensearchproject/opensearch:1.2.4
        expose:
            - '9200'
        environment:
            - DISABLE_INSTALL_DEMO_CONFIG=true
            - DISABLE_SECURITY_PLUGIN=true
            - discovery.type=single-node
            - bootstrap.memory_lock=true
            - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
        volumes:
            - ./services/opensearch/data:/usr/share/opensearch/data
        networks:
            - default

    blackfire:
        container_name: ${CONTAINER_PREFIX}_blackfire
        image: blackfire/blackfire:2.5.2
        environment:
            - BLACKFIRE_LOG_LEVEL=${BLACKFIRE_LOG_LEVEL}
            - BLACKFIRE_SERVER_ID=${BLACKFIRE_SERVER_ID}
            - BLACKFIRE_SERVER_TOKEN=${BLACKFIRE_SERVER_TOKEN}
            - BLACKFIRE_CLIENT_ID=${BLACKFIRE_CLIENT_ID}
            - BLACKFIRE_CLIENT_TOKEN=${BLACKFIRE_CLIENT_TOKEN}
        external_links:
            - nginx:${PROJECT_NAME}.docker.loc
        expose:
            - '8307'
        networks:
            - default

networks:
    default:
        external: true
        name: ${PROJECT_NAME}
